/*-----------------------------------------------------------------------------------------
 * Class Name:AccountHandler
 * Description: This Class have been used to find and duplicate account creation.
 * Date: 04/08/2020
 * Author: Meeta Pramanik July 04 test
test Comment
----------------------------------------- -------------------------------------------------*/
/*----------Metho Nametest AdditionsaSSDSAD----SAAS Application------*/
public class AccountHandler {
//july 4th for Demo purpose

    public static Account insertNewAccount(String name) {
        Account a = new Account();
        a.Name = name;
        //jfhvhagfsukfgh
        try
        {
            insert a;
        } catch (Exception e) {
            return null;
        }
        return a;
// addressing UST 001 Reg Details to test the release change
    }

}