!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        01jNzW0K-Questionaire:
          path: dataset/01jNzW0K-Questionaire
          prefix: ncino
          standardFeature: false
          versions:
            Rel 2024_07 v1:
              modifiedDate: '2025-09-09 10:42:27'
